import io
from typing import Dict, Any
from datetime import datetime
<<<<<<< HEAD

=======
>>>>>>> 6233cd8c1c0c25e0cc1ce26e6f7b0051542ecf79

async def _get_extended_stats(db: Any) -> Dict[str, Any]:
    today_midnight = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
    total_users = await db["Users"].count_documents({})
    dau = await db["Users"].count_documents({"last_active": {"$gte": today_midnight}})
    total_groups = await db["Groups"].count_documents({"Status": "Active"})
    total_fiat = await db["fiat_rates"].count_documents({})

    users_list = await db["Users"].find().to_list(length=None)
    total_reqs = sum(u.get("stats", {}).get("total_requests", 0) for u in users_list)

    errors_today = 0
    from app.config import LOGS_DIR
<<<<<<< HEAD

=======
>>>>>>> 6233cd8c1c0c25e0cc1ce26e6f7b0051542ecf79
    error_log_path = LOGS_DIR / "errors.log"
    if error_log_path.exists():
        today_str = datetime.now().strftime("%Y-%m-%d")
        try:
            with open(error_log_path, "r", encoding="utf-8") as f:
                lines = f.readlines()
                errors_today = sum(1 for line in lines if line.startswith(today_str))
        except Exception:
            pass

    db_stats = await db.command("dbstats")
    size_mb = db_stats.get("dataSize", 0) / (1024 * 1024)

    return {
        "Total Users": total_users,
        "DAU": dau,
        "Total Groups": total_groups,
        "Total Fiat Rates": total_fiat,
        "Total Requests": total_reqs,
        "Errors Today": errors_today,
        "DB Size (MB)": round(size_mb, 2),
    }


async def export_stats_csv(db: Any) -> io.BytesIO:
    """Generate a CSV export of current statistics."""
    import csv

    stats = await _get_extended_stats(db)

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Metric", "Value"])
    for k, v in stats.items():
        writer.writerow([k, v])

    return io.BytesIO(output.getvalue().encode("utf-8"))


async def export_stats_markdown(db: Any) -> io.BytesIO:
    """Generate a Markdown export of current statistics."""
    stats = await _get_extended_stats(db)

    md_content = "# System Statistics Report\n\n## Overview\n"
    for k, v in stats.items():
        md_content += f"- **{k}:** `{v}`\n"

    md_content += "\n*Generated by finances bot.*\n"
    return io.BytesIO(md_content.encode("utf-8"))
